version: '3.2'
services:
  challenge-api:
    build: .
    environment:
      SERVER_ADDR: ":8080"
      MONGO_URL: "mongodb://root:devpw@mongo:27017"
    ports:
    - "8080:8080"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devpw
      MONGO_INITDB_DATABASE: swapidb
    command: --smallfiles
    volumes:
    - ./dev_env/initialize-db.js:/docker-entrypoint-initdb.d/initialize-db.js
    ports:
    - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpw
      MONGO_INITDB_DATABASE: swapidb